version: '1.0.1'

services:
  web:
    build: 
      context: .
    ports:
      - 8000:3000
    volumes:
      - ./:/app
  
  mysqldb:
    image: mysql
    ports:
    - 3307:3307
    environment:
    - MYSQL_ROOT_PASSWORD=p@ssw0rd1
    volumes:
    - mysql:/var/lib/mysql
    - mysql_config:/etc/mysql
  
volumes:
  mysql:
  mysql_config: